### ISSUE TITLE
AESH

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#1]
- EP : `Accompagnant des élèves en situation de handicap`
- MT : 29
- NH : A partir de septembre 2014, ce terme désigne les `AVS` (Auxiliaire de vie scolaire) diplômé-e-s.

**A finaliser par Sylvie**

**Comment by CNRHRLaPepiniere** [comment]
NH : à partir de septembre 2014, ce terme remplace `AVS` (Assistant de vie scolaire) #26

**Comment by CNRHRLaPepiniere** [comment]
19 mai 2016  - Le président François Hollande a annoncé ce jeudi la transformation progressive des contrats aidés d'auxiliaires de vie scolaire (AVS), aujourd'hui limités dans le temps et précaires, en « contrats d'accompagnants des élèves en situation de handicap », lors de la 4e Conférence nationale du handicap. Il semblerait donc que AVS soit toujours d'usage en parrallèle à AESH.
