### ISSUE TITLE
Habileté sociale

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#105]
Utilisé en "autisme" et ergo

**Comment by CNRHRLaPepiniere** [comment]
Les habiletés sociales sont habituellement définies comme étant la capacité de démontrer un comportement approprié dans une variété de contextes comme à la maison, à l’école ou au travail et dans la société en général (Brown, 2003). Douaire (2008), dans sa thèse de doctorat, retient la définition de Michelson et al. (1986), qui intègre les différentes composantes des habiletés sociales :
    Les habiletés sociales sont principalement développées par apprentissage (par exemple via l’observation, le modelage);
    les habiletés sociales comprennent des comportements spécifiques et discrets, verbaux et non verbaux;
    les habiletés sociales se composent d’initiations et de réponses appropriées et efficaces;
    les habiletés sociales maximisent les renforcements sociaux;
    les habiletés sociales sont de nature interactive et impliquent des réactions efficaces et appropriées (par exemple un timing d’un comportement spécifique, une réciprocité); et
    les déficits et excès dans le fonctionnement social peuvent être spécifiés et représenter les cibles d’une intervention (Douaire, 2008, p. 11).
https://educationspecialisee.ca/habiletessociales/
Suggestion MT26 sous SOCIETE

**Comment by Nicolas-L** [comment]
MT : 03
TG : `Développement cognitif`
