### ISSUE TITLE
Amour

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#11]
Terme validé

**Comment by Nicolas-L** [comment]
MT : `Développement psychoaffectif`
TG : ?

Il manque le TG, je ré-ouvre le ticket
Je pense que nous l'avions déterminé, est-ce que quelqu'un s'en souvient ?

**Comment by CNRHRLaPepiniere** [comment]
Je pense TG `EMOTION`

**Comment by Nicolas-L** [comment]
MT : `Développement psychoaffectif`
TG : `EMOTION`
