### ISSUE TITLE
Oralité

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#128]
Dans le sens de l'Oralité alimentaire.
A réfléchir

**Comment by CNRHRLaPepiniere** [comment]
L'oralité correspond à l'ensemble des fonctions dévouées à la bouche, les deux fonctions majeures étant le langage et l'alimentation. Les troubles de l'oralité se caractérisent par une hypersensiblité ou hyposensibilité sensorielle concernant les goûts et les odeurs.
https://orthophonie.ooreka.fr/astuce/voir/549511/troubles-de-l-oralite.
Proposition MT02 TS de visage ?

**Comment by Nicolas-L** [comment]
MT : 09
