### ISSUE TITLE
Animal

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#13]
**Terme validé** : 
- MT : 38
- Note d'application : S'utilise dans le cadre de la `Recherche appliquée`. Ne pas utiliser ce terme pour `Zoothérapie` et `Relation Homme-Animal`.

**Comment by Nicolas-L** [comment]
**Remarque :** 
Il manque le TG => je ré-ouvre le ticket

**Comment by CNRHRLaPepiniere** [comment]
Je pense à `RECHERCHE MEDICALE` comme TG.
