### ISSUE TITLE
Unité d'enseignement maternelle (UEM)

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#174]
A définir

> Plan Autisme - Unité   d'Enseignement en Maternelle pour enfants avec troubles du spectre autistique   - Offre de scolarisation pour les enfants avec TSA - Instruction   interministérielle du 10 juin 2016.
--

**Comment by SandrineDR** [comment]
instruction interministérielle du 10 juin 2016

**Comment by Laplainemssh** [comment]
MT : 23

TG : `Enseignement adapté`

NE : Offre de scolarisation pour les enfants avec trouble du spectre autistique. Instruction interministérielle du 10 juin 2016.
