### ISSUE TITLE
Auxiliaire de vie scolaire

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#26]
- Terme Obsolète
- NH : Depuis septembre 2015, AVS (Assistant de vie scolaire) devient AESH (#1) 

A finaliser par Sylvie

**Comment by CNRHRLaPepiniere** [comment]
NA : `AVS` : Auxiliaire de vie scolaire (Attention AVS : Auxiliaire de vie sociale existe également)
NH : Devient `AESH` en septembre 2014. 
La distinction se fait au niveau du recrutement avec désormais l'obligation de détenir un diplôme dans le domaine de l'aide à la personne.

**Comment by Nicolas-L** [comment]
Assistant => Auxiliaire (descriptif du terme à modifier dans le thésaurus)
