### ISSUE TITLE
CIM 11

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#38]
- Note historique  : Inclut la CIM jusqu'à la CIM 10
- TG `CIM` TS `CIM 11` - (ne pas développer le sigle `Classification Internationale de la maladie`).

**Comment by Laplainemssh** [comment]
Je pense que ces classifications (comme la CIF) sont généralement connues et utilisées sous leur sigle. A maintenir donc

**Comment by Nicolas-L** [comment]
MT : 39
