### ISSUE TITLE
Comorbidité

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#45]
TS de `PATHOLOGIE` - Stéphanie G. vérifie la définition exacte. Si il s'agit d'évolution de maladie : mettre en TS de `EVOLUTION DE MALADIE` ;  `[MT] 06 - DIAGNOSTIC`

**Comment by sgcnrhr-es** [comment]
Définition Larousse : "Association de 2 maladies psychiques ou physiques fréquemment observée dans la population (sans causalité établie, contrairement aux complications) ; état qui en résulte."
Il ne s'agit donc pas d'une évolution de la maladie.
Pour aider peut-être à le situer, dans le thésaurus Santépsy (Asco), le descripteur existe dans le champ sémantique MEDECINE, sous le terme générique MALADIE et EP pathologies organiques associées.

**Comment by Nicolas-L** [comment]
TS de `PATHOLOGIE`
