### ISSUE TITLE
Comportements-problèmes / Comportements-défis

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#46]

**Comment by EGCNSA** [comment]
Vu dans le rapport Piveteau:
« Dans l’expression "troubles du comportement", le mot « troubles » introduit donc une dangereuse ambiguïté ... Même si elle est courante, cette formulation devrait être fermement évitée. Le rapport adoptera, pour désigner ces manifestation
[terminologie_rapport_piveteau.docx](https://github.com/reseau-doc/thesaurus-handicap/files/519884/terminologie_rapport_piveteau.docx)
s comportementales ... les expressions de « comportements-problèmes » ou de « comportements – défis », qui font aujourd’hui consensus. »

**Comment by Nicolas-L** [comment]
Descripteur retenu : `Comportement-problème`
MT : `Développement psychoaffectif` : MT 04
TG : `Comportement`
