### ISSUE TITLE
Dossier Médical Personnel

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#65]
A vérifier, argumenter

**Comment by Laplainemssh** [comment]
Suite à la loi de modernisation de notre système de santé, décret du 15 juillet 2016, le 
Dossier Médical Personnel a changé de nom et devient le Dossier médical partagé #177 .

**Comment by Nicolas-L** [comment]
Pour mémo :
- Je passe ce terme en [TO]
- Création du terme `Dossier médical partagé` #177 pour le remplacer définitivement
