### ISSUE TITLE
Agénésie

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#8]
Terme validé
A faire confirmer par Christiane B.

**Comment by Nicolas-L** [comment]
MT : `Anatomie - Stades de développement`
TG : ?

Il manque le TG, je ré-ouvre le ticket
Je pense que nous l'avions déterminé, est-ce que quelqu'un s'en souvient ?

**Comment by CNRHRLaPepiniere** [comment]
MT02
TG `EMBRYON` je crois
