### ISSUE TITLE
Autonomisation

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#89]
- Est remplacé par `Empowerment` #88 
- Devient EM d'`Empowerment`
- MT : 26

**Comment by Nicolas-L** [comment]
Est-ce qu'on ne pourrait pas plutôt le mettre en Terme Associé d'`Empowerment` ?

**Comment by Laplainemssh** [comment]
Oui, cela permettrait de ne pas chambouler la structure du thésaurus.

**Comment by Nicolas-L** [comment]
A rediscuter, je rouvre.
- Incidences sur les notices déjà indexées avec ce termes
- Si on confirme : Placer le terme dans _2. Descripteur V.2.0 Supprimé_
