### ISSUE TITLE
Risque psychosocial

### ISSUE THREAD

**Issue by MCLMSSH** [reseau-doc/thesaurus-handicap#93]
Micro thésaurus 24. 
Spécifique de `Milieu professionnel`

**Comment by Laplainemssh** [comment]
Petite précision sur la proposition de MCLMSSH. C'est effectivement un nouveau terme qui ne figure pas sur la liste des 200 termes candidats sur lesquels nous travaillons actuellement. Nous en tiendrons compte quand on débutera le travail sur les "R"

**Comment by Nicolas-L** [comment]
TS de `Condition de travail`
