### ISSUE TITLE
Détresse Psychologique

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-doc/thesaurus-handicap#96]
A argumenter par MSSH

**Comment by Laplainemssh** [comment]
Souvent utilisé dans les titres das articles, ce terme est lié à l'émotion, à un état de stress sans troubles psychologique. Je le propose dans le MT 05 spécifique ou au même niveau que stress.

**Comment by Laplainemssh** [comment]
Terme refusé. A priori, pas une notion psy précise.
